var _yt_www={};(function(m){var window=this;var qa,ra;m.aa=function(a){return function(){return m.ba[a].apply(this,arguments)}};m.ca=function(a){return void 0!==a};m.l=function(a,b,c){a=a.split(".");c=c||m.ea;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&m.ca(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};m.n=function(a,b){for(var c=a.split("."),d=b||m.ea,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};m.fa=function(){};m.ga=function(a){a.getInstance=function(){return a.gb?a.gb:a.gb=new a}};
m.ha=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};m.ia=function(a){return"array"==m.ha(a)};m.ka=function(a){var b=m.ha(a);return"array"==b||"object"==b&&"number"==typeof a.length};m.la=function(a){return"string"==typeof a};m.ma=function(a){return"number"==typeof a};m.na=function(a){return"function"==m.ha(a)};m.oa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};m.pa=function(a){return a[qa]||(a[qa]=++ra)};
var sa=function(a,b,c){return a.call.apply(a.bind,arguments)};var ta=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};m.q=function(a,b,c){m.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?sa:ta;return m.q.apply(null,arguments)};
m.r=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};m.t=function(a,b){function c(){}c.prototype=b.prototype;a.H=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[c].apply(a,h)}};m.va=function(a){m.va[" "](a);return a};
m.wa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,m.wa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};m.xa=function(a){return(0,window.encodeURIComponent)(String(a))};
m.ya=function(a){if(!za.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Aa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ba,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ca,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Da,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ea,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Fa,"&#0;"));return a};m.Ga=function(a,b){return-1!=a.indexOf(b)};m.Ha=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
m.Ia=function(a,b){for(var c=0,d=(0,m.Ja)(String(a)).split("."),e=(0,m.Ja)(String(b)).split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var k=d[h]||"",p=e[h]||"",v=RegExp("(\\d*)(\\D*)","g"),y=RegExp("(\\d*)(\\D*)","g");do{var N=v.exec(k)||["","",""],da=y.exec(p)||["","",""];if(0==N[0].length&&0==da[0].length)break;c=Ka(0==N[1].length?0:(0,window.parseInt)(N[1],10),0==da[1].length?0:(0,window.parseInt)(da[1],10))||Ka(0==N[2].length,0==da[2].length)||Ka(N[2],da[2])}while(0==c)}return c};
var Ka=function(a,b){return a<b?-1:a>b?1:0};m.La=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};m.Ma=function(a){var b=m.la(void 0)?m.Ha(void 0):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};m.Na=function(a,b,c){b=m.Oa(a,b,c);return 0>b?null:m.la(a)?a.charAt(b):a[b]};m.Oa=function(a,b,c){for(var d=a.length,e=m.la(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};
m.Pa=function(a,b){return 0<=(0,m.Qa)(a,b)};m.Ra=function(a,b){var c=(0,m.Qa)(a,b),d;(d=0<=c)&&m.Sa(a,c);return d};m.Sa=function(a,b){m.Ta.splice.call(a,b,1)};m.Ua=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};m.u=function(){this.jb=this.jb;this.wa=this.wa};m.Va=function(a,b){m.Wa(a,m.r(m.Xa,b))};m.Wa=function(a,b){a.wa||(a.wa=[]);a.wa.push(m.ca(void 0)?(0,m.q)(b,void 0):b)};m.Xa=function(a){a&&"function"==typeof a.dispose&&a.dispose()};
m.Ya=function(){m.u.call(this);this.xa=[];this.Ob={}};m.Za=function(a){$a(m.ab,arguments)};m.w=function(a,b){return a in m.ab?m.ab[a]:b};m.x=function(a,b){m.na(a)&&(a=m.bb(a));return window.setTimeout(a,b)};m.cb=function(a,b){m.na(a)&&(a=m.bb(a));return window.setInterval(a,b)};m.db=function(a){window.clearTimeout(a)};m.eb=function(a){window.clearInterval(a)};m.bb=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw m.fb(b),b;}}:a};
m.fb=function(a,b){var c=m.n("yt.www.errors.log");c?c(a,b):(c=m.w("ERRORS")||[],c.push([a,b]),m.Za("ERRORS",c))};m.gb=function(a){return a in m.hb};m.ib=function(a,b,c){var d=b||{};if(a=a in m.hb?m.hb[a]:c)for(var e in d)a=a.replace(new RegExp("\\$"+e,"gi"),function(){return d[e]});return a};var $a=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};
m.z=function(a,b,c){var d=jb();if(d){var e=d.subscribe(a,function(){if(!m.kb||m.kb!=e){var d=arguments,h=function(){lb[e]&&b.apply(c||window,d)};try{mb[a]?h():m.x(h,0)}catch(k){m.fb(k)}}},c);lb[e]=!0;nb[a]||(nb[a]=[]);nb[a].push(e);return e}return 0};m.ob=function(a){var b=jb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,m.A)(a,function(a){b.unsubscribeByKey(a);delete lb[a]}))};m.B=function(a,b){var c=jb();return c?c.publish.apply(c,arguments):!1};
m.pb=function(a,b){mb[a]=!0;var c=jb(),c=c?c.publish.apply(c,arguments):!1;mb[a]=!1;return c};var jb=function(){return m.n("yt.pubsub.instance_")};m.qb=function(a){if(a.classList)return a.classList;a=a.className;return m.la(a)&&a.match(/\S+/g)||[]};m.C=function(a,b){return a.classList?a.classList.contains(b):m.Pa(m.qb(a),b)};m.D=function(a,b){a.classList?a.classList.add(b):m.C(a,b)||(a.className+=0<a.className.length?" "+b:b)};
m.E=function(a,b){a.classList?a.classList.remove(b):m.C(a,b)&&(a.className=(0,m.rb)(m.qb(a),function(a){return a!=b}).join(" "))};m.sb=function(a,b,c){c?m.D(a,b):m.E(a,b)};m.tb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};m.ub=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};m.wb=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};m.xb=function(a,b){b in a&&delete a[b]};m.yb=function(a,b,c){if(b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};
m.zb=function(a){var b={},c;for(c in a)b[c]=a[c];return b};m.Ab=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Bb.length;f++)c=Bb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};m.Cb=function(a){var b=arguments.length;if(1==b&&m.ia(arguments[0]))return m.Cb.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};m.Db=function(){this.j="";this.k=Eb};
var Fb=function(a){return a instanceof m.Db&&a.constructor===m.Db&&a.k===Eb?a.j:"type_error:Const"};var Gb=function(){this.j="";this.k=Hb};var Ib=function(a){var b=new Gb;b.j=a;return b};var Jb=function(){this.j=Kb};var Lb=function(){this.j=Mb};var Nb=function(){this.j="";this.A=Ob;this.k=null};m.Pb=function(a){return a instanceof Nb&&a.constructor===Nb&&a.A===Ob?a.j:"type_error:SafeHtml"};
var Qb=function(a){function b(a){if(m.ia(a))(0,m.A)(a,b);else{if(!(a instanceof Nb)){var f=null;a.Jk&&(f=a.Zf());a=Rb(m.ya(a.$e?a.Ze():String(a)),f)}d+=m.Pb(a);a=a.Zf();0==c?c=a:0!=a&&c!=a&&(c=null)}}var c=0,d="";(0,m.A)(arguments,b);return Rb(d,c)};var Rb=function(a,b){var c=new Nb;c.j=a;c.k=b;return c};
m.Sb=function(a,b){var c=null,d="<"+a;if(b)for(var e in b){if(!Tb.test(e))throw Error('Invalid attribute name "'+e+'".');var f=b[e];if(null!=f){var h,k=a;h=e;if(f instanceof m.Db)f=Fb(f);else if("style"==h.toLowerCase()){if(!m.oa(f))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof f+" given: "+f);if(!(f instanceof Gb)){var k="",p=void 0;for(p in f){if(!/^[-_a-zA-Z0-9]+$/.test(p))throw Error("Name allows only [-_a-zA-Z0-9], got: "+p);var v=f[p];null!=
v&&(v instanceof m.Db?v=Fb(v):Ub.test(v)||(v="zClosurez"),k+=p+":"+v+";")}f=k?Ib(k):Vb}k=void 0;k=f instanceof Gb&&f.constructor===Gb&&f.k===Hb?f.j:"type_error:SafeStyle";f=k}else{if(/^on/i.test(h))throw Error('Attribute "'+h+'" requires goog.string.Const value, "'+f+'" given.');if(h.toLowerCase()in Wb)if(f instanceof Lb)f=f instanceof Lb&&f.constructor===Lb&&f.j===Mb?"":"type_error:TrustedResourceUrl";else if(f instanceof Jb)f=f instanceof Jb&&f.constructor===Jb&&f.j===Kb?"":"type_error:SafeUrl";
else throw Error('Attribute "'+h+'" on tag "'+k+'" requires goog.html.SafeUrl or goog.string.Const value, "'+f+'" given.');}f.$e&&(f=f.Ze());h=h+'="'+m.ya(String(f))+'"';d=d+(" "+h)}}e=void 0;m.ca(e)?m.ia(e)||(e=[e]):e=[];!0===Xb[a.toLowerCase()]?d+=">":(c=Qb(e),d+=">"+m.Pb(c)+"</"+a+">",c=c.Zf());(e=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(e)?c=0:c=null);return Rb(d,c)};m.Yb=function(a,b,c){return Math.min(Math.max(a,b),c)};m.Zb=function(a,b){this.width=a;this.height=b};
var $b=function(a){return m.Ga(m.ac,a)};var bc=function(){var a=m.ea.document;return a?a.documentMode:void 0};m.cc=function(a){return dc[a]||(dc[a]=0<=m.Ia(ec,a))};m.fc=function(a){return m.F&&m.gc>=a};m.G=function(a){return m.la(a)?window.document.getElementById(a):a};m.hc=function(a){return m.la(a)?window.document.getElementById(a):a};m.H=function(a,b){var c=b||window.document,d=null;c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=m.ic("*",a,b)[0];return d||null};
m.ic=function(a,b,c){var d=window.document;c=c||d;a=a&&"*"!=a?a.toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))return c.querySelectorAll(a+(b?"."+b:""));if(b&&c.getElementsByClassName){c=c.getElementsByClassName(b);if(a){for(var d={},e=0,f=0,h;h=c[f];f++)a==h.nodeName&&(d[e++]=h);d.length=e;return d}return c}c=c.getElementsByTagName(a||"*");if(b){d={};for(f=e=0;h=c[f];f++)a=h.className,"function"==typeof a.split&&m.Pa(a.split(/\s+/),b)&&(d[e++]=h);d.length=e;return d}return c};
m.jc=function(a,b){m.tb(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in kc?a.setAttribute(kc[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})};m.lc=function(a,b,c){return m.mc(window.document,arguments)};
m.mc=function(a,b){var c=b[0],d=b[1];if(!nc&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',m.ya(d.name),'"');if(d.type){c.push(' type="',m.ya(d.type),'"');var e={};m.Ab(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(m.la(d)?c.className=d:m.ia(d)?c.className=d.join(" "):m.jc(c,d));2<b.length&&m.oc(a,c,b,2);return c};
m.oc=function(a,b,c,d){function e(c){c&&b.appendChild(m.la(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];!m.ka(f)||m.oa(f)&&0<f.nodeType?e(f):(0,m.A)(pc(f)?m.Ua(f):f,e)}};m.qc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};var rc=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
var sc=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};m.tc=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};var pc=function(a){if(a&&"number"==typeof a.length){if(m.oa(a))return"function"==typeof a.item||"string"==typeof a.item;if(m.na(a))return"function"==typeof a.item}return!1};m.uc=function(a,b,c,d){c||(a=a.parentNode);c=null==d;for(var e=0;a&&(c||e<=d);){if(b(a))return a;a=a.parentNode;e++}return null};
m.vc=function(a){return function(){return a}};m.wc=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};m.xc=function(){};m.yc=function(a){if(a instanceof m.xc)return a;if("function"==typeof a.eb)return a.eb(!1);if(m.ka(a)){var b=0,c=new m.xc;c.next=function(){for(;;){if(b>=a.length)throw m.zc;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");};
m.Ac=function(a,b,c){if(m.ka(a))try{(0,m.A)(a,b,c)}catch(d){if(d!==m.zc)throw d;}else{a=m.yc(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(e){if(e!==m.zc)throw e;}}};m.Bc=function(a){if(m.ka(a))return m.Ua(a);a=m.yc(a);var b=[];m.Ac(a,function(a){b.push(a)});return b};m.Cc=function(a,b,c,d,e,f,h){var k="";a&&(k+=a+":");c&&(k+="//",b&&(k+=b+"@"),k+=c,d&&(k+=":"+d));e&&(k+=e);f&&(k+="?"+f);h&&(k+="#"+h);return k};
m.Dc=function(a){if(Ec){Ec=!1;var b=m.ea.location;if(b){var c=b.href;if(c&&(c=m.Fc(c))&&c!=b.hostname)throw Ec=!0,Error();}}return a.match(Gc)};m.Hc=function(a){return a?(0,window.decodeURI)(a):a};m.Fc=function(a){return m.Hc(m.Dc(a)[3]||null)};m.Ic=function(a){a=m.Dc(a);return m.Cc(null,null,null,null,a[5],a[6],a[7])};m.Jc=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
m.Kc=function(a,b,c){if(m.ia(b))for(var d=0;d<b.length;d++)m.Kc(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",m.xa(b))};var Lc=function(a,b){for(var c in b)m.Kc(c,b[c],a);return a};m.Mc=function(a){a=Lc([],a);a[0]="";return a.join("")};m.Nc=function(a,b){return m.Jc(Lc([a],b))};m.Oc=function(a,b,c){a&&(c?a&&(a=m.lc("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),m.tc(a).body.appendChild(a)):Pc(a,b))};
var Pc=function(a,b){var c=new window.Image,d=""+Qc++;Rc[d]=c;c.onload=c.onerror=function(){b&&Rc[d]&&b();delete Rc[d]};c.src=a;c=eval("null")};m.Sc=function(a,b,c){Tc(c)[a]=b||(0,m.I)();b||Uc(a);m.w("CSI_LOG_ON_TICK")&&Vc(!1,c)};var Wc=function(a,b){Xc(void 0).yt_sts=a;m.Sc("_start",b,void 0)};var Yc=function(a){a=Tc(a);if(a.aft)return a.aft;for(var b=m.w("TIMING_AFT_KEYS",["ol"]),c=b.length,d=0;d<c;d++){var e=a[b[d]];if(e)return e}return window.NaN};
var Zc=function(a){return Math.round($c.timing.navigationStart+a)};
var ad=function(a){var b=window.location.protocol,c=$c.getEntriesByType("resource"),d=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.googleapis.com/css?family=")})[0],c=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});d&&0<d.startTime&&0<d.responseEnd&&(a.wfcs=Zc(d.startTime),a.wfce=Zc(d.responseEnd));c&&0<c.startTime&&0<c.responseEnd&&(a.wffs=Zc(c.startTime),a.wffe=Zc(c.responseEnd))};
var Vc=function(a,b){var c=m.w("TIMING_ACTION"),d=Tc(b);if(c&&d._start&&Yc(b)){var c=!0,e=m.w("TIMING_WAIT",[]);if(!a&&e.length)for(var f=0,h=e.length;f<h;++f)if(!(e[f]in d)){c=!1;break}if(c||b){var k;e=Tc(b);d=bd(b).span;f=Xc(b);if(c=m.n("yt.timing.reportbuilder_")){if(c=c(e,d,f,b))cd(c),dd(b),ed();k=window.NaN}else{c={v:2,s:"youtube",action:m.w("TIMING_ACTION")};$c.now&&$c.timing&&(h=$c.timing.navigationStart+$c.now(),h=Math.round((0,m.I)()-h),f.yt_hrd=h);var h=m.w("TIMING_INFO")||{},p;for(p in h)f[p]=
h[p];p=f.srt;delete f.srt;var v;p||0===p||(v=$c.timing||{},p=Math.max(0,v.responseStart-v.navigationStart),(0,window.isNaN)(p)&&f.pt&&(p=f.pt));if(p||0===p)f.srt=p;f.h5jse&&(h=window.location.protocol+m.n("ytplayer.config.assets.js"),(h=$c.getEntriesByName?$c.getEntriesByName(h)[0]:null)?f.h5jse=Math.round(f.h5jse-h.responseEnd):delete f.h5jse);e.aft=Yc(b);h=e._start;if(!fd){v||(v=$c.timing||{});var y;i:if(y=v,y.msFirstPaint)y=Math.max(0,y.msFirstPaint);else{var N=window.chrome;if(N&&(N=N.loadTimes,
m.na(N))){var N=N(),da=1E3*Math.min(N.requestTime||window.Infinity,N.startLoadTime||window.Infinity),da=window.Infinity===da?0:y.navigationStart-da;y=Math.max(0,Math.round(1E3*N.firstPaintTime+da)||0);break i}y=0}0<y&&y>h&&(e.fpt=y);y=v.redirectEnd-v.redirectStart;0<y&&(d.rtime_=y);y=v.domainLookupEnd-v.domainLookupStart;0<y&&(d.dns_=y);y=v.connectEnd-v.connectStart;0<y&&(d.tcp_=y);y=v.connectEnd-v.secureConnectionStart;v.secureConnectionStart&&0<y&&(d.stcp_=y);y=v.responseStart-v.requestStart;0<
y&&(d.req_=y);y=v.responseEnd-v.responseStart;0<y&&(d.rcv_=y);m.w("EXP_WEBFONT_ENABLED")&&$c.getEntriesByType&&ad(e);fd=!0}m.w("CSI_MORE")&&(f.p=m.w("CLIENT_PROTOCOL")||"unknown",f.t=m.w("CLIENT_TRANSPORT")||"unknown");for(var ja in f)"_"!=ja.charAt(0)&&(c[ja]=f[ja]);ja={};v=[];for(var ua in e)"_"!=ua.charAt(0)&&(y=Math.max(Math.round(e[ua]-h),0),ja[ua]=y,v.push(ua+"."+y));c.rt=v.join(",");ua={};v=[];for(k in d)"_"!=k.charAt(0)&&(ua[k]=d[k],v.push(k+"."+d[k]));c.it=v.join(",");(k=m.n("ytdebug.logTiming"))&&
k(c,ja,ua);dd(b);ed();m.w("EXP_DEFER_CSI_PING")?(gd(),hd=c,id=m.x(gd,0)):cd(c);k=ja.aft+(p||0)}return k}}return window.NaN};var jd=function(a){return m.w("CSI_LOG_ON_TICK")?window.NaN:Vc(!1,a)};var cd=function(a){m.w("EXP_DEFER_CSI_PING")&&(m.db(id),hd=null);var b="https:"==window.location.protocol?"https://gg.google.com/csi":"http://csi.gstatic.com/csi",c="",d;for(d in a)c+="&"+d+"="+a[d];m.Oc(b+"?"+c.substring(1))};var gd=function(a){hd&&(a&&(hd.yt_fss=a),cd(hd))};var Tc=function(a){return bd(a).tick};
var Xc=function(a){return bd(a).info};var bd=function(a){return m.n("ytcsi."+(a||"")+"data_")||dd(a)};var dd=function(a){var b={tick:{},span:{},info:{}};m.l("ytcsi."+(a||"")+"data_",b,void 0);return b};m.kd=function(){return!!m.n("yt.scheduler.instance")};m.ld=function(){return m.kd()&&m.C(window.document.body,"exp-js-scheduler-more")};
m.md=function(a,b){void 0===b&&(b=window.NaN);var c=m.n("yt.scheduler.instance.addJob");return c?((0,window.isNaN)(b)&&(b=0),c(a,0,b)):(0,window.isNaN)(b)?(a(),window.NaN):m.x(a,b||0)};m.nd=function(a,b){return m.md(a,b)};m.od=function(a){var b=m.n("yt.scheduler.instance.cancelJob");b?b(a):m.db(a)};m.pd=function(a){for(var b=0,c=a.length;b<c;b++)m.od(a[b])};m.qd=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.C=d?m.bb(d):null;this.B=e?m.bb(e):null;this.xa=[];this.k=this.A=0};
m.rd=function(a){m.ld()?(m.od(a.A),a.A=m.nd((0,m.q)(a.init,a))):a.init()};m.sd=function(a){a.name in td&&ud(a.name);td[a.name]={reqs:[],disable:(0,m.q)(a.disable,a)};(0,m.A)(a.deps,function(b){if(!(b in td))throw Error("Module "+b+" required by "+a.name);td[b].reqs.push(a.name)});a.enable()};var ud=function(a){if(a in td){var b=td[a];(0,m.A)(b.reqs,function(a){ud(a)});try{b.disable()}catch(c){}delete td[a]}};m.J=function(a,b){return a?a.dataset?a.dataset[m.vd(b)]:a.getAttribute("data-"+b):null};
m.wd=function(a,b){return a?a.dataset?m.vd(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b):!1};m.vd=function(a){return xd[a]||(xd[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};m.yd=function(a,b){var c=m.zd(a);window.spf.script.load(a,c,b)};m.Ad=function(a,b){var c=m.zd(a);window.spf.script.ignore(c,b)};m.Bd=function(a){a&&(m.la(a)?m.yd(a):m.ia(a)?(0,m.A)(a,function(a){m.Bd(a)}):m.tb(a,function(a,c){m.yd(c,function(){m.Bd(a)})}))};
m.zd=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(Cd,""),b=b.replace(Dd,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};var Ed=function(a,b){if(m.w("EVENTS_TRACKER_INSTALLED")){var c=Fd[a];if(!c){var d=window._gaq._getAsyncTracker("eventsPageTracker");if(!d)return;window._gaq.push(function(){c=d._createEventTracker(a);Fd[a]=c})}window._gaq.push(function(){c._trackEvent(b,void 0,void 0)})}};
var Gd=function(a){a=m.Hd(a);return m.Id(a)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};m.Id=function(a){return null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1};m.Hd=function(a){a=(0,m.Jd)(a);return null===a?null:a.split(".").reverse()};m.Kd=function(a,b,c){Ed(a,b||"null");m.Ld("a="+a+(b?"&"+b:"").replace(/\//g,"&"),c)};m.Ld=function(a,b){m.Oc("/gen_204?"+a,b)};
m.Md=function(){return m.Nd?"Webkit":m.Od?"Moz":m.F?"ms":m.Pd?"O":null};m.Qd=function(){return m.Nd?"-webkit":m.Od?"-moz":m.F?"-ms":m.Pd?"-o":null};m.Rd=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};m.Sd=function(a,b){return a&&b?b instanceof m.Rd?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};
m.Td=function(a,b){var c=Ud[b];if(!c){var d=m.La(b),c=d;void 0===a.style[d]&&(d=m.Md()+m.Ma(d),void 0!==a.style[d]&&(c=d));Ud[b]=c}return c};m.Vd=function(a,b){var c=m.tc(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""};m.Wd=function(a,b){return m.Vd(a,b)||(a.currentStyle?a.currentStyle[b]:null)||a.style&&a.style[b]};
m.Xd=function(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}m.F&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b};m.Yd=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};m.Zd=function(a){return m.$d(ae,a)};
m.$d=function(a,b){if("none"!=m.Wd(b,"display"))return a(b);var c=b.style,d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";var h=a(b);c.display=d;c.position=f;c.visibility=e;return h};var ae=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=m.Nd&&!b&&!c;return m.ca(b)&&!d||!a.getBoundingClientRect?new m.Zb(b,c):(a=m.Xd(a),new m.Zb(a.right-a.left,a.bottom-a.top))};m.be=function(a,b){a.style.display=b?"":"none"};
var ce=function(a){a=a||{};this.url=a.url||"";this.urlV8=a.url_v8||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||m.zb(de);this.assets=a.assets||{};this.attrs=a.attrs||m.zb(ee);this.params=a.params||m.zb(fe);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};m.ge=function(a){a instanceof ce||(a=new ce(a));return a};
var he=function(){return null!=m.ie};m.je=function(){return m.ie?m.ie.invoke():null};m.ke=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,m.A)(a.childNodes,function(a){b.appendChild(m.ke(a))}):b.innerHTML=a.innerHTML;return b};
m.le=function(a){if(a=a||window.event){for(var b in a)b in me||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;this.na=a;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:
a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;"MozMousePixelScroll"==this.type?(this.wheelDeltaX=a.axis==a.HORIZONTAL_AXIS?a.detail:0,this.wheelDeltaY=a.axis==a.HORIZONTAL_AXIS?0:a.detail):window.opera?(this.wheelDeltaX=0,this.wheelDeltaY=a.detail):0==a.wheelDelta%120?"WebkitTransform"in window.document.documentElement.style?window.chrome&&0==window.navigator.platform.indexOf("Mac")?(this.wheelDeltaX=a.wheelDeltaX/
-30,this.wheelDeltaY=a.wheelDeltaY/-30):(this.wheelDeltaX=a.wheelDeltaX/-1.2,this.wheelDeltaY=a.wheelDeltaY/-1.2):(this.wheelDeltaX=0,this.wheelDeltaY=a.wheelDelta/-1.6):(this.wheelDeltaX=a.wheelDeltaX/-3,this.wheelDeltaY=a.wheelDeltaY/-3);this.Hk=a.pageX;this.Ik=a.pageY}};m.ne=function(a,b,c,d){return m.wb(m.oe,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
m.K=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=m.ne(a,b,c,d);if(e)return e;var e=++pe.count+"",f=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),h;h=f?function(d){d=new m.le(d);if(!m.uc(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new m.le(b);b.currentTarget=a;return c.call(a,b)};h=m.bb(h);m.oe[e]=[a,b,c,h,d];a.addEventListener?"mouseenter"==b&&f?a.addEventListener("mouseover",
h,d):"mouseleave"==b&&f?a.addEventListener("mouseout",h,d):"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style?a.addEventListener("MozMousePixelScroll",h,d):a.addEventListener(b,h,d):a.attachEvent("on"+b,h);return e};m.qe=function(a){this.j=a};m.re=function(a){a=(a.j.cookie||"").split(m.se);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
m.te=function(a,b,c){m.ue.set(""+a,b,c,"/","youtube.com")};m.ve=function(a,b){return m.ue.get(""+a,b)};m.we=function(a,b){a=!!a;m.l("_lactCookie",a,window);if(null==m.n("_lact",window)){if(a&&b){var c=m.ve("ACTIVITY","-1");m.l("_lact",(0,window.parseInt)(c,10),window)}else m.l("_lact",-1,window),xe();m.K(window.document,"keypress",xe);m.K(window.document,"mousedown",xe);m.K(window.document,"mouseup",xe)}};
var xe=function(){var a=m.n("_lact",window);null==a&&(m.we(),a=m.n("_lact",window));var b=(0,m.I)();m.l("_lact",b,window);m.n("_lactCookie",window)&&1E3<=b-a&&m.te("ACTIVITY",""+b)};m.ye=function(){var a=m.n("_lact",window);return null==a?-1:Math.max((0,m.I)()-a,0)};m.ze=function(a,b,c){var d=m.Fc(a);if(d==m.Fc(window.location.href)||!d&&0==a.lastIndexOf("/",0))if(a=m.Ic(a),d=a.indexOf("#"),a=0>d?a:a.substr(0,d))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&Ae(a,b,c)):Ae(a,b)};
var Ae=function(a,b,c){for(var d=0,e=0;e<a.length;++e)d=31*d+a.charCodeAt(e),d%=4294967296;a="s_tempdata-"+d;c=c||5;b=b?m.Mc(b):"";m.te(a,b,c)};m.Be=function(a,b,c){c=c||"";window.location=m.Nc(a,b||{})+c};m.Ce=function(a,b){var c=window.ytspf||{};b&&m.ze(a,b);c.enabled?window.spf.navigate(a):m.Be(a)};m.De=function(a,b,c){var d=m.w("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&m.ze(a,b);if(c)return!1;m.Ce(a);return!0};var Ee=function(a){m.ea.setTimeout(function(){throw a;},0)};
var Fe=function(){var a=m.ea.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(a=function(){var a=window.document.createElement("iframe");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,m.q)(function(a){if(("*"==d||a.origin==
d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!$b("Trident")&&!$b("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(m.ca(c.next)){c=c.next;var a=c.Lp;c.Lp=null;a()}};return function(a){d.next={Lp:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("script")?function(a){var b=
window.document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){m.ea.setTimeout(a,0)}};var Ge=function(a,b){He||Ie();Je||(He(),Je=!0);Ke.push(new Me(a,b))};
var Ie=function(){if(m.ea.Promise&&m.ea.Promise.resolve){var a=m.ea.Promise.resolve();He=function(){a.then(Ne)}}else He=function(){var a=Ne;!m.na(m.ea.setImmediate)||m.ea.Window&&m.ea.Window.prototype.setImmediate==m.ea.setImmediate?(Oe||(Oe=Fe()),Oe(a)):m.ea.setImmediate(a)}};var Ne=function(){for(;Ke.length;){var a=Ke;Ke=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.re.call(c.scope)}catch(d){Ee(d)}}}Je=!1};var Me=function(a,b){this.re=a;this.scope=b};
m.Pe=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};m.Qe=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};m.Re=function(a,b){this.k=0;this.D=void 0;this.j=this.A=null;this.B=this.C=!1;try{var c=this;a.call(b,function(a){Se(c,2,a)},function(a){Se(c,3,a)})}catch(d){Se(this,3,d)}};m.Te=function(a){return new m.Re(function(b){b(a)})};
var Ue=function(a,b){if(0==a.k)if(a.A){var c=a.A;if(c.j){for(var d=0,e=-1,f=0,h;h=c.j[f];f++)if(h=h.Gf)if(d++,h==a&&(e=f),0<=e&&1<d)break;0<=e&&(0==c.k&&1==d?Ue(c,b):(d=c.j.splice(e,1)[0],Ve(c,d,3,b)))}}else Se(a,3,b)};var We=function(a,b){a.j&&a.j.length||2!=a.k&&3!=a.k||Xe(a);a.j||(a.j=[]);a.j.push(b)};
m.Ye=function(a,b,c,d){var e={Gf:null,Ln:null,Mn:null};e.Gf=new m.Re(function(a,h){e.Ln=b?function(c){try{var e=b.call(d,c);a(e)}catch(v){h(v)}}:a;e.Mn=c?function(b){try{var e=c.call(d,b);!m.ca(e)&&b instanceof Ze?h(b):a(e)}catch(v){h(v)}}:h});e.Gf.A=a;We(a,e);return e.Gf};
var Se=function(a,b,c){if(0==a.k){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(m.Qe(c)){a.k=1;c.then(a.F,a.L,a);return}if(m.oa(c))try{var d=c.then;if(m.na(d)){$e(a,c,d);return}}catch(e){b=3,c=e}}a.D=c;a.k=b;Xe(a);3!=b||c instanceof Ze||af(a,c)}};var $e=function(a,b,c){function d(b){f||(f=!0,a.L(b))}function e(b){f||(f=!0,a.F(b))}a.k=1;var f=!1;try{c.call(b,e,d)}catch(h){d(h)}};var Xe=function(a){a.C||(a.C=!0,Ge(a.J,a))};
var Ve=function(a,b,c,d){if(2==c)b.Ln(d);else{if(b.Gf)for(;a&&a.B;a=a.A)a.B=!1;b.Mn(d)}};var af=function(a,b){a.B=!0;Ge(function(){a.B&&bf.call(null,b)})};var Ze=function(a){m.wa.call(this,a)};var cf=function(a){this.A=a;this.k=null;var b=this;a.then(function(a){b.k=a})};
var df=function(a,b){var c=b||{},d=ef().then(function(b){return b(a,{apiKey:c.of||c.apiKey,environment:c.pf||c.environment,helpCenterPath:c.qA||c.helpCenterPath,locale:c.locale||c.locale,productData:c.rA||c.productData,receiverUri:c.sA||c.receiverUri,theme:c.theme||c.theme,window:c.window||c.window})});return new cf(d)};
var ef=function(){if(ff)return ff;var a=m.n("help.service.Lazy.create");return a?ff=m.Te(a):ff=(new m.Re(function(a,c){var d=window.document.createElement("script");d.async=!0;d.src="https://www.gstatic.com/inproduct_help/service/lazy.min.js";d.onload=d.onreadystatechange=function(){d.readyState&&"loaded"!=d.readyState&&"complete"!=d.readyState||a(null)};d.onerror=c;(window.document.head||window.document.getElementsByTagName("head")[0]).appendChild(d)})).then(function(){var a=m.n("help.service.Lazy.create");
if(!a)throw Error("Failed to load help.service.Lazy.create from https://www.gstatic.com/inproduct_help/service/lazy.min.js");return a})};var gf=function(a,b,c){a.A.then(function(a){a[b].apply(a,c)})};var hf=function(a){a=a.match(/[\d]+/g);if(!a)return"";a.length=3;return a.join(".")};var jf=function(a){return(a=a.exec(m.ac))?a[1]:""};
var kf=function(){this.A=this.k=this.j=0;this.B="";var a=m.n("window.navigator.plugins"),b=m.n("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,f=c.length;e<f;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.B=b;b=a;this.j=b[0];this.k=b[1];this.A=b[2];if(0>=this.j){var h,k,p,v;if(m.lf)try{h=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(y){h=null}else p=window.document.body,v=window.document.createElement("object"),v.setAttribute("type","application/x-shockwave-flash"),h=p.appendChild(v);if(h&&"GetVariable"in h)try{k=h.GetVariable("$version")}catch(N){k=""}p&&v&&p.removeChild(v);(h=k||"")?(h=h.split(" ")[1].split(","),
h=[(0,window.parseInt)(h[0],10)||0,(0,window.parseInt)(h[1],10)||0,(0,window.parseInt)(h[2],10)||0]):h=[0,0,0];this.j=h[0];this.k=h[1];this.A=h[2]}};var mf=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.j>b[0]||a.j==b[0]&&a.k>b[1]||a.j==b[0]&&a.k==b[1]&&a.A>=b[2]};
var nf=function(a){return-1<a.B.indexOf("Gnash")&&-1==a.B.indexOf("AVM2")||9==a.j&&1==a.k||9==a.j&&0==a.k&&1==a.A?!1:9<=a.j};var of=function(a){return m.pf?!mf(a,11,2):m.qf?!mf(a,11,3):!nf(a)};m.rf=function(a,b){(a=m.G(a))&&a.style&&(m.be(a,b),m.sb(a,"hid",!b))};m.L=function(a){(0,m.A)(arguments,function(a){m.rf(a,!0)})};
var sf=function(a,b){var c=m.w("FEEDBACK_LOCALE_LANGUAGE"),d=m.tf,e=m.w("FEEDBACK_LOCALE_EXTRAS",{});a?m.Ab(d,a):m.Ab(d,e);try{var f,h=m.n("yt.player.getPlayerByElement");(f=h?h("player-api"):null)&&f.pauseVideo&&f.pauseVideo();var k=kf.getInstance();d.flashVersion=k.getVersion().join(".");f&&(d.playback_id=f.getVideoData().cpn)}catch(p){}b&&m.Ab(d,{trackingParam:b});return{helpCenterPath:"/youtube",locale:c,productData:d}};
var uf=function(){var a=m.w("SESSION_INDEX"),b=m.w("FEEDBACK_BUCKET_ID"),c={abuseLink:"https://support.google.com/youtube/bin/answer.py?answer=140536",customZIndex:"2000000005"};a&&(c.authuser=a+"");b&&(c.bucket=b);return c};m.vf=function(a,b){try{var c=(a||"59")+"",d=sf(b),e=uf();df(c,d).B(e);return!1}catch(f){return!0}};
m.wf=function(a,b,c,d,e,f,h,k){b=(b||"59")+"";d=sf(d,h);a={context:c,anchor:a,enableSendFeedback:f?!1:!0,defaultHelpArticleId:k};m.Ab(a,uf());try{var p=df(b,d);if(e&&!xf)try{p.j(a),xf=!0}catch(v){}p.C(a);return!1}catch(y){return!0}};m.yf=function(a,b,c,d){return m.wf(void 0,d,b,c,void 0,void 0,void 0,a)};m.zf=function(){var a=m.ve("PREF");if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(m.Af[d]=c.toString())}};
var Bf=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};var Cf=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};m.Df=function(a){a=void 0!==m.Af[a]?m.Af[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};m.Ef=function(a,b){return!!((m.Df("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
var Ff=function(a,b,c){if(b){a=m.la(a)?m.hc(a):a;c=m.ge(c);var d=m.zb(c.attrs);d.tabindex=0;var e=m.zb(c.params);e.flashvars=m.Mc(c.args);if(m.lf){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var f in d)b.setAttribute(f,d[f]);for(f in e)d=window.document.createElement("param"),d.setAttribute("name",f),d.setAttribute("value",e[f]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");
b.setAttribute("name",d.id);for(f in d)b.setAttribute(f,d[f]);for(f in e)b.setAttribute(f,e[f])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};m.Gf=function(a,b){a=m.la(a)?m.hc(a):a;b=m.ge(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=Hf();mf(c,b.minVersion)?(c=If(b,c),Ff(a,c,b)):Jf(a,b,c)};
var Kf=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=m.ge(a);var d=!!b,e=m.G(a.attrs.id),f=e?e.parentNode:null;if(e&&f){if(window!=window.top){var h=null;if(window.document.referrer){var k=window.document.referrer.substring(0,128);Gd(k)||(h=k)}else h="unknown";h&&(d=!0,a.args.framer=h)}h=Hf();if(mf(h,a.minVersion)){var k=If(a,h),p="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(p=e.getAttribute("src")||e.movie);(p!=k||d)&&Ff(f,k,a);of(h)&&Lf()}else Jf(f,a,h);c&&c()}else m.x(function(){Kf(a,
b,c)},50)}};var Jf=function(a,b,c){0==c.j&&b.fallback?b.fallback():0==c.j&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+m.ib("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};var If=function(a,b){var c;(c=nf(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!mf(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.urlV8||a.url};
var Hf=function(){var a=kf.getInstance(),b=m.zf.getInstance();b.set("fv",a.getVersion().join("."));b.save();return a};var Lf=function(){var a=m.G("flash10-promo-div"),b=m.Ef(m.zf.getInstance(),107);a&&!b&&m.L(a)};m.Mf=function(a,b){var c=a.match(Nf);window.spf.style.load(a,c?c[1]:"",b)};
var Of=function(){if(2.2==Pf)return!0;var a;a=m.n("yt.player.utils.videoElement_");a||(a=window.document.createElement("video"),m.l("yt.player.utils.videoElement_",a,void 0));try{return!(!a||!a.canPlayType||!a.canPlayType('video/mp4; codecs="avc1.42001E, mp4a.40.2"')&&!a.canPlayType('video/webm; codecs="vp8.0, vorbis"'))}catch(b){return!1}};var Qf=function(){};m.Rf=function(){};m.Sf=function(a){this.j=a};m.Tf=function(){var a=null;try{a=window.localStorage||null}catch(b){}this.j=a};
var Uf=function(){var a=null;try{a=window.sessionStorage||null}catch(b){}this.j=a};m.Vf=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};m.Wf=function(a){return m.Xf(new m.Yf(void 0),a)};
m.Yf=function(a){this.j=a};m.Xf=function(a,b){var c=[];Zf(a,b,c);return c.join("")};
var Zf=function(a,b,c){switch(typeof b){case "string":$f(b,c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(m.ia(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],Zf(a,a.j?a.j.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&
(c.push(d),$f(f,c),c.push(":"),Zf(a,a.j?a.j.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}};var $f=function(a,b){b.push('"',a.replace(ag,function(a){if(a in bg)return bg[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return bg[a]=e+b.toString(16)}),'"')};m.cg=function(a){this.j=a};var dg=function(a){this.j=a};var eg=function(a){this.data=a};var fg=function(a){return!m.ca(a)||a instanceof eg?a:new eg(a)};
var gg=function(a){this.j=a};m.hg=function(a){var b=a.creation;a=a.expiration;return!!a&&a<(0,m.I)()||!!b&&b>(0,m.I)()};m.ig=function(a){this.j=a};m.jg=function(a,b,c){var d=c&&0<c?c:0;c=d?(0,m.I)()+1E3*d:0;if((d=d?m.kg:m.lg)&&window.JSON){m.la(b)||(b=JSON.stringify(b,void 0));try{d.set(a,b,c)}catch(e){d.remove(a)}}};m.mg=function(a){if(!m.lg&&!m.kg||!window.JSON)return null;var b;try{b=m.lg.get(a)}catch(c){}if(!m.la(b))try{b=m.kg.get(a)}catch(d){}if(!m.la(b))return null;try{b=JSON.parse(b,void 0)}catch(e){}return b};
var ng=function(){var a={volume:100,muted:!1},b=m.mg("yt-player-volume")||{};a.volume=(0,window.isNaN)(b.volume)?100:m.Yb(b.volume,0,100);a.muted=void 0==b.muted?!1:b.muted;return a};
var og=function(a,b){m.u.call(this);this.A=this.vf=a;this.J=b;this.D=!1;this.j={};this.U=this.L=null;this.S=new m.Ya;m.Va(this,this.S);this.B={};this.C=this.X=this.k=this.Ba=this.ea=null;this.O=!1;this.ga=this.F=null;this.ba={};this.Fa=["onReady"];this.qa=null;this.Aa=0;this.T={};pg(this);this.ue("onVolumeChange",(0,m.q)(this.Xp,this));this.ue("onError",(0,m.q)(this.Wp,this));this.ue("onTabOrderChange",(0,m.q)(this.Vp,this));this.ue("WATCH_LATER_VIDEO_ADDED",(0,m.q)(this.Yp,this));this.ue("WATCH_LATER_VIDEO_REMOVED",
(0,m.q)(this.Zp,this))};
var qg=function(a,b){a.Ba=b;a.ea=b.clone();a.k=a.ea.attrs.id||a.k;"video-player"==a.k&&(a.k=a.J,a.ea.attrs.id=a.J);a.A.id==a.k&&(a.k=a.k+"-player",a.ea.attrs.id=a.k);var c=a.ea.args,d;(d=a.ea.args.eurl)||(d=(d=window.document.location.toString())&&-1!=d.search(rg)?window.document.referrer&&window.document.referrer.substring(0,128)||"unknown":d);c.eurl=d;a.ea.args.enablejsapi="1";a.ea.args.playerapiid=a.J;a.X||(a.X=sg(a,a.ea.args.jsapicallback||"onYouTubePlayerReady"));a.ea.args.jsapicallback=null;
if(c=a.ea.attrs.width)a.A.style.width=m.Yd(Number(c)||c,!0);if(c=a.ea.attrs.height)a.A.style.height=m.Yd(Number(c)||c,!0);a.A.style.overflow="hidden"};var tg=function(a){a.ea.loaded||(a.ea.loaded=!0,"0"!=a.ea.args.autoplay?a.j.loadVideoByPlayerVars(a.ea.args):a.j.cueVideoByPlayerVars(a.ea.args))};var ug=function(a){if(!m.ca(a.ea.disable.flash)){var b=a.ea.disable,c;c=mf(Hf(),a.ea.minVersion);b.flash=!c}return!a.ea.disable.flash};
var vg=function(a){var b=wg(a);b&&b.stopVideo&&b.stopVideo();if(ug(a)){var c=a.ea;b&&b.getUpdatedConfigurationData&&(b=m.ge(b.getUpdatedConfigurationData()),b.args.video_id==c.args.video_id&&(c=b));c.args.autoplay=1;c.args.html5_unavailable="1";qg(a,c);yg(a,"flash")}};
var yg=function(a,b){if(!a.ha()){if(!b){var c;if(!(c=!a.ea.html5&&ug(a))){if(!m.ca(a.ea.disable.html5)){if(c=Of())c=zg(a)||a.ea.assets.js;a.ea.disable.html5=!c;c||(a.ea.args.html5_unavailable="1")}c=!!a.ea.disable.html5}b=c?ug(a)?"flash":"unsupported":"html5"}("flash"==b?a.Iy:"html5"==b?a.Jy:a.Ky).call(a)}};var zg=function(a){var b=!0,c=wg(a);c&&a.ea&&(a=a.ea,b=m.J(c,"version")==a.assets.js);return b&&!!m.n("yt.player.Application.create")};
var wg=function(a){var b=m.G(a.k);!b&&a.A&&a.A.querySelector&&(b=a.A.querySelector("#"+a.k));return b};var Ag=function(a,b,c){var d=b[c];return function(){try{return a.qa=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&(e.message+=" ("+c+")",a.qa=e,m.fb(e,"WARNING"))}}};
var pg=function(a){a.D=!1;if(a.U)for(var b in a.B)a.U(b,a.B[b]);for(var c in a.T)m.db((0,window.parseInt)(c,10));a.T={};a.L=null;a.U=null;for(var d in a.j)a.j[d]=null;a.j.addEventListener=(0,m.q)(a.ue,a);a.j.removeEventListener=(0,m.q)(a.Dt,a);a.j.destroy=(0,m.q)(a.dispose,a);a.j.getLastError=(0,m.q)(a.Bt,a);a.j.getPlayerType=(0,m.q)(a.Ct,a);a.j.getCurrentVideoConfig=(0,m.q)(a.At,a);a.j.loadNewVideoConfig=(0,m.q)(a.kj,a);a.j.isReady=(0,m.q)(a.Et,a)};
var sg=function(a,b){var c=b;if("string"==typeof b){if(a.ba[b])return a.ba[b];c=function(){var a=m.n(b);a&&a.apply(m.ea,arguments)};a.ba[b]=c}return c?c:null};var Bg=function(a,b){var c="ytPlayer"+b+a.J;a.B[b]=c;m.ea[c]=function(c){var e=m.x(function(){a.ha()||(a.S.publish(b,c),m.xb(a.T,e.toString()))},0);m.yb(a.T,e.toString(),!0)};return c};var Cg=function(a){return(a=wg(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
var Dg=function(a){m.Sc("dcp");a.cancel();pg(a);a.C=null;a.ea&&(a.ea.loaded=!1);var b=wg(a);"html5"==Cg(a)?a.ga=b:b&&b.destroy&&b.destroy();m.qc(a.vf)};m.Eg=function(a,b){a=m.la(a)?m.hc(a):a;b=m.ge(b);var c=Fg+"_"+m.pa(a),d=Gg[c];if(d)return d.kj(b),d.j;d=new og(a,c);Gg[c]=d;m.B("player-added",d.j);m.Wa(d,m.r(Hg,d));m.x(function(){d.kj(b)},0);return d.j};var Ig=function(){for(var a in Gg){var b=Gg[a];b&&b.cancel()}};m.Jg=function(a){if(a=m.G(a))a=Fg+"_"+m.pa(a),(a=Gg[a])&&a.dispose()};
var Hg=function(a){Gg[a.getId()]=null};m.Kg=function(a){a=m.G(a);if(!a)return null;var b=Fg+"_"+m.pa(a),c=Gg[b];c||(c=new og(a,b),Gg[b]=c);return c.j};
var Lg=function(){m.l("yt.abuse.botguardInitialized",he,void 0);m.l("yt.abuse.invokeBotguard",m.je,void 0);m.l("yt.player.exports.navigate",m.De,void 0);m.l("yt.player.embed",m.Eg,void 0);m.l("yt.player.destroy",m.Jg,void 0);m.l("yt.player.cancelAll",Ig,void 0);m.l("yt.player.getPlayerByElement",m.Kg,void 0);m.l("yt.player.exports.feedbackStart",m.vf,void 0);m.l("yt.player.exports.feedbackShowArticle",m.yf,void 0);m.l("yt.util.activity.init",m.we,void 0);m.l("yt.util.activity.getTimeSinceActive",
m.ye,void 0);m.l("yt.util.activity.setTimestamp",xe,void 0);var a=m.n("ytplayer.config");Mg(a);m.n("ytspf.enabled")&&(Ng=m.cb(Og,5E3),(a=m.Pg())?(a.addEventListener("onReady",Og),a.addEventListener("onStateChange",Og)):Qg("unable to init PP monitor"));m.w("PLAYER_SIZE_MONITORING")&&(Rg=Date.now(),Sg=m.cb(Tg,1E3),Ug.push(m.z("page-resize",Vg)))};var Vg=function(){Tg()};
var Tg=function(a){if(m.w("PLAYER_SIZE_MONITORING")){var b=Date.now(),c=b-Rg;if(!Wg()){var d=m.Zd(m.G("player-api"));a=a||"";if(!(d==Xg||d&&Xg&&d.width==Xg.width&&d.height==Xg.height))a="r";else if(3E4<c)a="wt";else if(!a)return;c=m.Mc({pw:(Xg||d).width,t:c,r:a,ei:m.w("EVENT_ID","")});m.Kd("persistentplayer",c,void 0);Xg=d}Rg=b}};var Wg=function(){var a=m.G("player");return!a||m.C(a,"off-screen")};
var Mg=function(a){Ig();if(a=a||null){var b=m.Pg(),c=!0,d=m.Yg;m.Yg=null;b&&b.getVideoData&&d&&(c=b.getVideoData(),c=!!d.fullscreen||c.video_id!=a.args.video_id||c.list!=a.args.list||c.video_id!=d.videoId||c.list!=d.listId);c?(Zg="",m.Eg("player-api",a)):b.playVideo();a=m.ge(a);a.loaded=!0}Og();m.l("ytplayer.config",a,void 0)};m.Pg=function(){var a=m.n("yt.player.getPlayerByElement");return a?a("player-api"):null};
var Og=function(){var a=m.Pg();if(a){var b=Wg(),c=1==(a&&a.isReady()?a.getPlayerState():void 0),d="watch"==m.w("PAGE_NAME");c&&!d&&(Qg("PP playing off watch (paused)"),a.pauseVideo());b&&d?Qg("PP off-screen on watch"):b||d||Qg("PP !off-screen off watch")}};var Qg=function(a){var b=m.w("PAGE_NAME");b&&(b=[b,Zg,m.n("_spf_state.nav-counter")],a+="("+b.join(",")+")",m.l("yt.www.persistentplayer.issue",a,void 0),m.fb(Error(a),"WARNING"))};
var $g=function(){m.Sc("ol");ah("init");var a=m.w("PAGE_NAME");a&&ah("init-"+a);jd()};var ah=function(a){m.kd()?bh.push(m.md(m.r(m.pb,a),0)):m.B(a)};var ch=function(){m.pd(bh);bh.length=0;var a=m.w("PAGE_NAME");a&&m.pb("dispose-"+a);m.pb("dispose")};var dh=function(){$g()};var eh=function(){m.w("TIMING_REPORT_ON_UNLOAD")&&Vc(!0);m.w("EXP_DEFER_CSI_PING")&&gd("u");ch()};
var fh=function(a,b,c,d,e){for(var f=window.document.getElementsByTagName("script"),h=!1,k=0,p=f.length;k<p;k++)if(0<f[k].src.indexOf("/debug-")){h=!0;break}h&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),m.fb(e))};var gh=function(){hh=1;ih=0;m.w("TIMING_REPORT_ON_UNLOAD")&&Vc(!0);m.w("EXP_DEFER_CSI_PING")&&gd("n");dd(void 0);ed();m.w("CSI_TRACK_ON_BEGIN")&&Wc("nb");Uc("mark_navigation_requested");jh(kh);m.pb("navigate")};
var lh=function(a){a=a.detail.part||a.detail.partial;m.Sc("nc"+ih);++ih;var b=1==hh;hh=2;b?(jh(mh),nh()):jh(oh);(a=a.data&&a.data.swfcfg)&&ph(a)};var qh=function(){};var rh=function(a){a=a.detail.response;var b=1==hh;hh=3;b&&(jh(sh),nh());(a=a.data&&a.data.swfcfg)&&ph(a)};
var th=function(a){m.Sc("nd");a=a.detail.response;m.uh=a.cacheKey;a=a.timing;var b=window._spf_state,b=b&&b["nav-counter"]||0;Xc(void 0).yt_nav=b;Wc("ne",a.responseStart);b=Math.max(0,a.responseStart-a.navigationStart);Xc(void 0).srt=b;b=a.spfCached?"hot":"warm";Xc(void 0).yt_lt=b;b=+!!a.spfPrefetched;Xc(void 0).yt_pft=b;a=a.responseStart-a.fetchStart;bd(void 0).span.req=a;jh(vh);window.document.getElementById("content").style.height="";$g();hh=0};
var wh=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),m.fb(a)};var xh=function(a){a=m.Mc({spfreload:"1",url:a.detail.url,reason:a.detail.reason});m.Ld(a)};var yh=function(){zh()};var Ah=function(){};
var nh=function(){window.scroll(0,0);var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");ch();for(var b in m.ab)delete m.ab[b];m.l("ytplayer.config",null,void 0);if((a=m.Pg())&&a.stopVideo){if(a.stopVideo(),a=a.getLastError())Zg=a,(a=m.G("movie_player"))&&a.stopVideo?(a.stopVideo(),Zg="recovered"):Zg="missing2"}else Zg="missing";Og()};var ph=function(a){"cfg"in Tc(void 0)||m.Sc("cfg");Mg(a)};
var jh=function(a){function b(){var b=a[0],e=a[1],f=a[2];c.className="";var h=c.style;h.transitionDuration=h.webkitTransitionDuration=b+"ms";h.width=e+"%";m.db(Bh);Bh=m.x(function(){c.className=f},b)}var c=window.document.getElementById("progress");c||(c=window.document.createElement("div"),c.id="progress",c.innerHTML="<dt><dd>",window.document.body.appendChild(c));m.ld()?(m.od(Ch),Ch=m.md(b,0)):(m.db(Bh),Bh=m.x(b,0))};
var zh=function(){var a=vh[0]+50;m.db(Bh);Bh=m.x(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};var Dh=function(){m.qd.call(this,"www/base");this.j=0};var Eh=function(a){(a=a.detail.name)&&ud(a)};m.ba=[];m.Fh=m.Fh||{};m.ea=this;qa="closure_uid_"+(1E9*Math.random()>>>0);ra=0;m.I=Date.now||function(){return+new Date};
Function.prototype.bind=Function.prototype.bind||function(a,b){if(1<arguments.length){var c=Array.prototype.slice.call(arguments,1);c.unshift(this,a);return m.q.apply(null,c)}return(0,m.q)(this,a)};m.va[" "]=m.fa;m.t(m.wa,Error);m.wa.prototype.name="CustomError";var Aa,Ba,Ca,Da,Ea,Fa,za;m.Ja=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};Aa=/&/g;Ba=/</g;Ca=/>/g;Da=/"/g;Ea=/'/g;Fa=/\x00/g;za=/[\x00&<>"']/;m.Gh=2147483648*Math.random()|0;m.Ta=Array.prototype;m.Qa=m.Ta.indexOf?function(a,b,c){return m.Ta.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(m.la(a))return m.la(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
m.Hh=m.Ta.lastIndexOf?function(a,b,c){return m.Ta.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(m.la(a))return m.la(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};m.A=m.Ta.forEach?function(a,b,c){m.Ta.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.la(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
m.rb=m.Ta.filter?function(a,b,c){return m.Ta.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=m.la(a)?a.split(""):a,k=0;k<d;k++)if(k in h){var p=h[k];b.call(c,p,k,a)&&(e[f++]=p)}return e};m.Ih=m.Ta.map?function(a,b,c){return m.Ta.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=m.la(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};
m.Jh=m.Ta.reduce?function(a,b,c,d){d&&(b=(0,m.q)(b,d));return m.Ta.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;(0,m.A)(a,function(c,h){e=b.call(d,e,c,h,a)});return e};m.Kh=m.Ta.some?function(a,b,c){return m.Ta.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.la(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1};
m.Lh=m.Ta.every?function(a,b,c){return m.Ta.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=m.la(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};m.u.prototype.jb=!1;m.u.prototype.ha=function(){return this.jb};m.u.prototype.dispose=function(){this.jb||(this.jb=!0,this.N())};m.u.prototype.N=function(){if(this.wa)for(;this.wa.length;)this.wa.shift()()};m.t(m.Ya,m.u);m.g=m.Ya.prototype;m.g.$o=1;m.g.Mh=0;m.g.subscribe=function(a,b,c){var d=this.Ob[a];d||(d=this.Ob[a]=[]);var e=this.$o;this.xa[e]=a;this.xa[e+1]=b;this.xa[e+2]=c;this.$o=e+3;d.push(e);return e};m.g.unsubscribe=function(a,b,c){if(a=this.Ob[a]){var d=this.xa;if(a=m.Na(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.Jb(a)}return!1};
m.g.Jb=function(a){if(0!=this.Mh)return this.j||(this.j=[]),this.j.push(a),!1;var b=this.xa[a];if(b){var c=this.Ob[b];c&&m.Ra(c,a);delete this.xa[a];delete this.xa[a+1];delete this.xa[a+2]}return!!b};m.g.publish=function(a,b){var c=this.Ob[a];if(c){this.Mh++;for(var d=Array(arguments.length-1),e=1,f=arguments.length;e<f;e++)d[e-1]=arguments[e];e=0;for(f=c.length;e<f;e++){var h=c[e];this.xa[h+1].apply(this.xa[h+2],d)}this.Mh--;if(this.j&&0==this.Mh)for(;c=this.j.pop();)this.Jb(c);return 0!=e}return!1};
m.g.clear=function(a){if(a){var b=this.Ob[a];b&&((0,m.A)(b,this.Jb,this),delete this.Ob[a])}else this.xa.length=0,this.Ob={}};m.g.va=m.aa(3);m.g.N=function(){m.Ya.H.N.call(this);delete this.xa;delete this.Ob;delete this.j};m.ab=window.yt&&window.yt.config_||{};m.l("yt.config_",m.ab,void 0);m.l("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);m.hb=window.yt&&window.yt.msgs_||{};m.l("yt.msgs_",m.hb,void 0);m.lf="Microsoft Internet Explorer"==window.navigator.appName;var Mh=m.n("yt.pubsub.instance_")||new m.Ya;m.Ya.prototype.subscribe=m.Ya.prototype.subscribe;m.Ya.prototype.unsubscribeByKey=m.Ya.prototype.Jb;m.Ya.prototype.publish=m.Ya.prototype.publish;m.Ya.prototype.clear=m.Ya.prototype.clear;m.l("yt.pubsub.instance_",Mh,void 0);var lb=m.n("yt.pubsub.subscribedKeys_")||{};m.l("yt.pubsub.subscribedKeys_",lb,void 0);var nb=m.n("yt.pubsub.topicToKeys_")||{};m.l("yt.pubsub.topicToKeys_",nb,void 0);var mb=m.n("yt.pubsub.isSynchronous_")||{};
m.l("yt.pubsub.isSynchronous_",mb,void 0);m.kb=m.n("yt.pubsub.skipSubId_")||null;m.l("yt.pubsub.skipSubId_",m.kb,void 0);var Bb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");var Xb=m.Cb("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));m.Nh=RegExp("^[^\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");m.Oh=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");m.Db.prototype.$e=!0;m.Db.prototype.Ze=function(){return this.j};m.Db.prototype.toString=function(){return"Const{"+this.j+"}"};var Eb={};Gb.prototype.$e=!0;var Hb={};Gb.prototype.Ze=function(){return this.j};var Vb=Ib(""),Ub=/^[-.%_!# a-zA-Z0-9]+$/;Jb.prototype.$e=!0;Jb.prototype.Ze=function(){return""};Jb.prototype.Jk=!0;Jb.prototype.Zf=function(){return 1};var Kb={};Lb.prototype.$e=!0;Lb.prototype.Ze=function(){return""};Lb.prototype.Jk=!0;Lb.prototype.Zf=function(){return 1};var Mb={};var Tb,Wb,Ph,Ob;Nb.prototype.Jk=!0;Nb.prototype.Zf=function(){return this.k};Nb.prototype.$e=!0;Nb.prototype.Ze=function(){return this.j};Tb=/^[a-zA-Z0-9-]+$/;Wb=m.Cb("action","cite","data","formaction","href","manifest","poster","src");Ph=m.Cb("embed","iframe","link","object","script","style","template");Ob={};m.Qh=Rb("",0);m.g=m.Zb.prototype;m.g.clone=function(){return new m.Zb(this.width,this.height)};m.g.isEmpty=m.aa(5);m.g.ceil=m.aa(7);m.g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};m.g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};m.g.scale=function(a,b){var c=m.ma(b)?b:a;this.width*=a;this.height*=c;return this};t:{var Rh=m.ea.navigator;if(Rh){var Sh=Rh.userAgent;if(Sh){m.ac=Sh;break t}}m.ac=""};var Uh,ec,dc,Zh;m.Pd=$b("Opera")||$b("OPR");m.F=$b("Trident")||$b("MSIE");m.Od=$b("Gecko")&&!m.Ga(m.ac.toLowerCase(),"webkit")&&!($b("Trident")||$b("MSIE"));m.Nd=m.Ga(m.ac.toLowerCase(),"webkit");m.Nd&&$b("Mobile");m.qf=$b("Macintosh");m.pf=$b("Windows");m.Th=$b("Linux")||$b("CrOS");Uh=m.ea.navigator||null;m.Vh=!!Uh&&m.Ga(Uh.appVersion||"","X11");m.Wh=$b("Android");m.Xh=$b("iPhone")&&!$b("iPod")&&!$b("iPad");m.Yh=$b("iPad");
ec=function(){var a="",b;if(m.Pd&&m.ea.opera)return a=m.ea.opera.version,m.na(a)?a():a;m.Od?b=/rv\:([^\);]+)(\)|;)/:m.F?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:m.Nd&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(m.ac))?a[1]:"");return m.F&&(b=bc(),b>(0,window.parseFloat)(a))?String(b):a}();dc={};Zh=m.ea.document;m.gc=Zh&&m.F?bc()||("CSS1Compat"==Zh.compatMode?(0,window.parseInt)(ec,10):5):void 0;var nc;nc=!m.F||m.fc(9);m.$h=!m.Od&&!m.F||m.F&&m.fc(9)||m.Od&&m.cc("1.9.1");m.ai=m.F&&!m.cc("9");m.bi=m.F||m.Pd||m.Nd;m.ci=m.F&&!m.fc(9);var kc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};m.di=m.vc(!1);m.ei=m.vc(!0);m.zc="StopIteration"in m.ea?m.ea.StopIteration:Error("StopIteration");m.xc.prototype.next=function(){throw m.zc;};m.xc.prototype.eb=function(){return this};var Gc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,Ec=m.Nd;var rg=/^https?:\/\/([A-Za-z0-9-]{1,63}\.)*(corp\.google\.com|borg\.google\.com|prod\.google\.com|video\.google\.com|youtube\.com|youtube\.googleapis\.com|youtube-nocookie\.com|youtubeeducation\.com)(:[0-9]+)?\/+embed\/+/;var Rc={},Qc=0,fi=m.n("yt.net.ping.workerUrl_")||null;m.l("yt.net.ping.workerUrl_",fi,void 0);var fd,hd,id;var $c=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance||{},ed=(0,m.q)($c.clearResourceTimings||$c.webkitClearResourceTimings||$c.mozClearResourceTimings||$c.msClearResourceTimings||$c.oClearResourceTimings||m.fa,$c),Uc=$c.mark?function(a){$c.mark(a)}:m.fa;m.g=m.qd.prototype;m.g.ix=function(){2==this.k||this.init()};m.g.enable=function(){this.k=1;(0,m.A)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.ix,this),this.subscribe("dispose-"+a,this.dispose,this),m.w("PAGE_NAME")==a&&m.rd(this))},this)};m.g.init=function(){m.ld()&&m.od(this.A);this.k=2;this.C&&this.C()};m.g.dispose=function(){this.k=3;m.od(this.A);this.B&&this.B()};m.g.disable=function(){this.k=4;this.clear();try{this.dispose()}catch(a){m.fb(a)}};
m.g.subscribe=function(a,b,c){a=m.z(a,b,c);this.xa.push(a);return a};m.g.clear=function(){m.ob(this.xa);this.xa=[]};var td=m.n("yt.modules.registry_")||{};m.l("yt.modules.registry_",td,void 0);var xd={};var Cd=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,Dd=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;var Fd={};m.Jd=m.Fc;m.g=m.Rd.prototype;m.g.clone=function(){return new m.Rd(this.top,this.right,this.bottom,this.left)};m.g.contains=function(a){return m.Sd(this,a)};m.g.ceil=m.aa(6);m.g.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};m.g.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
m.g.scale=function(a,b){var c=m.ma(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};var Ud={};var de={enablejsapi:1},ee={},fe={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};ce.prototype.clone=function(){var a=new ce,b;for(b in this){var c=this[b];"object"==m.ha(c)?a[b]=m.zb(c):a[b]=c}return a};m.ie=null;m.gi=m.Nd?"webkit":m.Od?"moz":m.F?"ms":m.Pd?"o":"";m.hi=m.n("yt.dom.getNextId_");if(!m.hi){m.hi=function(){return++ii};m.l("yt.dom.getNextId_",m.hi,void 0);var ii=0};m.g=m.le.prototype;m.g.na=null;m.g.type="";m.g.target=null;m.g.relatedTarget=null;m.g.currentTarget=null;m.g.data=null;m.g.source=null;m.g.state=null;m.g.keyCode=0;m.g.charCode=0;m.g.altKey=!1;m.g.ctrlKey=!1;m.g.shiftKey=!1;m.g.clientX=0;m.g.clientY=0;m.g.wheelDeltaX=0;m.g.wheelDeltaY=0;m.g.rotation=0;m.g.scale=1;m.g.changedTouches=null;m.g.preventDefault=m.aa(8);m.g.stopPropagation=m.aa(9);m.g.stopImmediatePropagation=m.aa(10);
var me={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1};m.oe=m.n("yt.events.listeners_")||{};m.l("yt.events.listeners_",m.oe,void 0);var pe=m.n("yt.events.counter_")||{count:0};m.l("yt.events.counter_",pe,void 0);m.se=/\s*;\s*/;m.g=m.qe.prototype;m.g.isEnabled=m.aa(11);m.g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');m.ca(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,m.I)()+1E3*c)).toUTCString();this.j.cookie=a+"="+b+e+d+c+f};
m.g.get=function(a,b){for(var c=a+"=",d=(this.j.cookie||"").split(m.se),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};m.g.remove=function(a,b,c){var d=m.ca(this.get(a));this.set(a,"",0,b,c);return d};m.g.Sa=m.aa(12);m.g.ya=m.aa(13);m.g.isEmpty=m.aa(4);m.g.va=m.aa(2);m.g.uf=m.aa(14);m.g.clear=function(){for(var a=m.re(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};m.ue=new m.qe(window.document);m.ue.k=3950;var Oe;var He,Je=!1,Ke=[];m.Re.prototype.then=function(a,b,c){return m.Ye(this,m.na(a)?a:null,m.na(b)?b:null,c)};m.Pe(m.Re);m.Re.prototype.cancel=function(a){0==this.k&&Ge(function(){var b=new Ze(a);Ue(this,b)},this)};m.Re.prototype.F=function(a){this.k=0;Se(this,2,a)};m.Re.prototype.L=function(a){this.k=0;Se(this,3,a)};m.Re.prototype.J=function(){for(;this.j&&this.j.length;){var a=this.j;this.j=[];for(var b=0;b<a.length;b++)Ve(this,a[b],this.k,this.D)}this.C=!1};var bf=Ee;m.t(Ze,m.wa);Ze.prototype.name="cancel";var ff=null;cf.prototype.B=function(a){gf(this,"startFeedback",arguments)};cf.prototype.C=function(a){gf(this,"startHelp",arguments)};cf.prototype.j=function(a){gf(this,"loadChatSupport",arguments)};var ji=!1,ki="";
if(window.navigator.plugins&&window.navigator.plugins.length){var li=window.navigator.plugins["Shockwave Flash"];li&&(ji=!0,li.description&&(ki=hf(li.description)));window.navigator.plugins["Shockwave Flash 2.0"]&&(ji=!0,ki="2.0.0.11")}else if(window.navigator.mimeTypes&&window.navigator.mimeTypes.length){var mi=window.navigator.mimeTypes["application/x-shockwave-flash"];(ji=mi&&mi.enabledPlugin)&&(ki=hf(mi.enabledPlugin.description))}else try{var ni=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),ji=
!0,ki=hf(ni.GetVariable("$version"))}catch(aaa){try{ni=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),ji=!0,ki="6.0.21"}catch(baa){try{ni=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash"),ji=!0,ki=hf(ni.GetVariable("$version"))}catch(caa){}}}m.oi=ji;m.pi=ki;var qi,ri,si,ti,ui,vi,wi,zi,Ci;wi=vi=ui=ti=si=ri=qi=!1;var xi=m.ac;xi&&(-1!=xi.indexOf("Firefox")?qi=!0:-1!=xi.indexOf("Camino")?ri=!0:-1!=xi.indexOf("iPad")?ti=!0:-1!=xi.indexOf("iPhone")||-1!=xi.indexOf("iPod")?si=!0:-1!=xi.indexOf("Chrome")?vi=!0:-1!=xi.indexOf("Android")?ui=!0:-1!=xi.indexOf("Safari")&&(wi=!0));m.yi=qi;zi=ri;m.Ai=si;m.Bi=ti;Ci=ui;m.Di=vi;m.Ei=wi;m.Fi=function(){if(m.yi)return jf(/Firefox\/([0-9.]+)/);if(m.F||m.Pd)return ec;if(m.Di)return jf(/Chrome\/([0-9.]+)/);if(m.Ei)return jf(/Version\/([0-9.]+)/);if(m.Ai||m.Bi){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(m.ac))return a[1]+"."+a[2]}else{if(Ci)return(a=jf(/Android\s+([0-9.]+)/))?a:jf(/Version\/([0-9.]+)/);if(zi)return jf(/Camino\/([0-9.]+)/)}return""}();m.ga(kf);kf.prototype.getVersion=function(){return[this.j,this.k,this.A]};m.Gi=m.wc(function(){if(m.F)return m.cc("10.0");var a=window.document.createElement("div"),b=m.Qd(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");b={style:c};if(!Tb.test("div"))throw Error("Invalid tag name <div>.");if("div"in Ph)throw Error("Tag name <div> is not allowed for SafeHtml.");b=m.Sb("div",b);a.innerHTML=m.Pb(b);a=a.firstChild;b=a.style[m.La("transition")];return""!=("undefined"!==typeof b?b:a.style[m.Td(a,"transition")]||"")});var xf;m.tf={};xf=!1;m.ga(m.zf);m.Af=m.n("yt.prefs.UserPrefs.prefs_")||{};m.l("yt.prefs.UserPrefs.prefs_",m.Af,void 0);m.g=m.zf.prototype;m.g.get=function(a,b){Cf(a);Bf(a);var c=void 0!==m.Af[a]?m.Af[a].toString():null;return null!=c?c:b?b:""};m.g.set=function(a,b){Cf(a);Bf(a);if(null==b)throw"ExpectedNotNull";m.Af[a]=b.toString()};m.g.remove=function(a){Cf(a);Bf(a);delete m.Af[a]};m.g.save=function(){var a;a=[];for(var b in m.Af)a.push(b+"="+(0,window.escape)(m.Af[b]));a=a.join("&");m.te("PREF",a,63072E3)};
m.g.clear=function(){m.Af={}};var Nf=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var Pf;var Hi=m.ac,Hi=Hi.toLowerCase();if(m.Ga(Hi,"android")){var Ii=Hi.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(Ii)Pf=Number(Ii[1]);else{var Ji={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},Ki=Hi.match("("+m.ub(Ji).join("|")+")");Pf=Ki?Ji[Ki[0]]:0}}else Pf=void 0;m.t(m.Rf,Qf);m.Rf.prototype.va=m.aa(1);m.Rf.prototype.clear=function(){var a=m.Bc(this.eb(!0)),b=this;(0,m.A)(a,function(a){b.remove(a)})};m.t(m.Sf,m.Rf);m.g=m.Sf.prototype;m.g.isAvailable=function(){if(!this.j)return!1;try{return this.j.setItem("__sak","1"),this.j.removeItem("__sak"),!0}catch(a){return!1}};m.g.set=function(a,b){try{this.j.setItem(a,b)}catch(c){if(0==this.j.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};m.g.get=function(a){a=this.j.getItem(a);if(!m.la(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};m.g.remove=function(a){this.j.removeItem(a)};
m.g.va=m.aa(0);m.g.eb=function(a){var b=0,c=this.j,d=new m.xc;d.next=function(){if(b>=c.length)throw m.zc;var d;d=c.key(b++);if(a)return d;d=c.getItem(d);if(!m.la(d))throw"Storage mechanism: Invalid value was encountered";return d};return d};m.g.clear=function(){this.j.clear()};m.g.key=function(a){return this.j.key(a)};m.t(m.Tf,m.Sf);m.t(Uf,m.Sf);var bg={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},ag=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;m.cg.prototype.set=function(a,b){m.ca(b)?this.j.set(a,m.Wf(b)):this.j.remove(a)};m.cg.prototype.get=function(a){var b;try{b=this.j.get(a)}catch(c){return}if(null!==b)try{return m.Vf(b)}catch(d){throw"Storage: Invalid value was encountered";}};m.cg.prototype.remove=function(a){this.j.remove(a)};m.t(dg,m.cg);dg.prototype.set=function(a,b){dg.H.set.call(this,a,fg(b))};dg.prototype.k=function(a){a=dg.H.get.call(this,a);if(!m.ca(a)||a instanceof Object)return a;throw"Storage: Invalid value was encountered";};dg.prototype.get=function(a){if(a=this.k(a)){if(a=a.data,!m.ca(a))throw"Storage: Invalid value was encountered";}else a=void 0;return a};m.t(gg,dg);gg.prototype.set=function(a,b,c){if(b=fg(b)){if(c){if(c<(0,m.I)()){gg.prototype.remove.call(this,a);return}b.expiration=c}b.creation=(0,m.I)()}gg.H.set.call(this,a,b)};gg.prototype.k=function(a,b){var c=gg.H.k.call(this,a);if(c)if(!b&&m.hg(c))gg.prototype.remove.call(this,a);else return c};m.t(m.ig,gg);var Li,Mi;Li=new m.Tf;m.kg=Li.isAvailable()?new m.ig(Li):null;Mi=new Uf;m.lg=Mi.isAvailable()?new m.ig(Mi):null;m.t(og,m.u);m.g=og.prototype;m.g.getId=function(){return this.J};m.g.kj=function(a,b){this.ha()||(qg(this,a),yg(this,b),this.D&&tg(this))};m.g.At=function(){return this.Ba};
m.g.Jy=function(){if(!this.O){var a=zg(this);a&&"html5"==Cg(this)?(this.C="html5",this.D||this.Je()):(Dg(this),this.C="html5",a&&this.ga?(this.vf.appendChild(this.ga),this.Je()):(this.ea.loaded=!0,this.F=(0,m.q)(function(){var a=this.vf,c=this.ea.clone();m.n("yt.player.Application.create")(a,c);this.Je()},this),this.O=!0,a?this.F():(m.yd(this.ea.assets.js,this.F),m.Mf(this.ea.assets.css))))}};
m.g.Iy=function(){var a=this.ea.clone();a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==Cg(this)?(this.C="flash",this.D||Kf(a,!1,(0,m.q)(this.Je,this))):(Dg(this),this.C="flash",this.ea.loaded=!0,m.Gf(this.vf,a),this.Je())};
m.g.Je=function(){var a=wg(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(c){}if(b)if(this.O=!1,a.isNotServable&&a.isNotServable())vg(this);else{pg(this);this.D=!0;a=wg(this);a.addEventListener&&(this.L=Ag(this,a,"addEventListener"));a.removeEventListener&&(this.U=Ag(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),d=0;d<b.length;d++){var e=b[d];this.j[e]||(this.j[e]=Ag(this,a,e))}for(var f in this.B)this.L(f,this.B[f]);tg(this);
this.X&&this.X(this.j);this.S.publish("onReady",this.j)}else this.Aa=m.x((0,m.q)(this.Je,this),50)};m.g.Et=function(){return this.D};m.g.ue=function(a,b){if(!this.ha()){var c=sg(this,b);if(c){if(!m.Pa(this.Fa,a)&&!this.B[a]){var d=Bg(this,a);this.L&&this.L(a,d)}this.S.subscribe(a,c);"onReady"==a&&this.D&&m.x(m.r(c,this.j),0)}}};m.g.Dt=function(a,b){if(!this.ha()){var c=sg(this,b);c&&this.S.unsubscribe(a,c)}};
m.g.Vp=function(a){a=a?sc:rc;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||(b.focus(),b!=window.document.activeElement));)b=a(b)};m.g.Xp=function(a){var b={};b.volume=(0,window.isNaN)(a.volume)?ng().volume:m.Yb(a.volume,0,100);b.muted=void 0==a.muted?ng().muted:a.muted;m.jg("yt-player-volume",b,2592E3)};m.g.Wp=function(a){5==a&&vg(this)};m.g.Yp=function(a){m.B("WATCH_LATER_VIDEO_ADDED",a)};m.g.Zp=function(a){m.B("WATCH_LATER_VIDEO_REMOVED",a)};
m.g.Ky=function(){Dg(this);this.C="unsupported";var a='Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>',b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a='Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/"> Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>');
b=this.ea.messages.player_fallback||a;a=m.G("player-unavailable");m.G("unavailable-submessage")&&a&&(m.G("unavailable-submessage").innerHTML=b,(b=m.H("icon",a))&&m.wd(b,"icon")&&(b.src=m.J(b,"icon")),m.E(a,"hid"),m.D(m.G("player"),"off-screen-trigger"))};m.g.Ct=function(){return this.C||Cg(this)};m.g.Bt=function(){return this.qa};m.g.cancel=function(){this.F&&m.Ad(this.ea.assets.js,this.F);m.db(this.Aa);this.O=!1};
m.g.N=function(){Dg(this);this.ba=null;for(var a in this.B)m.ea[this.B[a]]=null;this.j=null;delete this.vf;delete this.A;this.ea&&(this.Ba=this.ea=this.ea.fallback=null);og.H.N.call(this)};var Gg={},Fg="player_uid_"+(1E9*Math.random()>>>0);var Ni=m.n("yt.abuse.botguardInitialized")||he;m.l("yt.abuse.botguardInitialized",Ni,void 0);var Oi=m.n("yt.abuse.invokeBotguard")||m.je;m.l("yt.abuse.invokeBotguard",Oi,void 0);var Pi=m.n("yt.player.exports.navigate")||m.De;m.l("yt.player.exports.navigate",Pi,void 0);var Qi=m.n("yt.player.embed")||m.Eg;m.l("yt.player.embed",Qi,void 0);var Ri=m.n("yt.player.destroy")||m.Jg;m.l("yt.player.destroy",Ri,void 0);var Si=m.n("yt.player.cancelAll")||Ig;m.l("yt.player.cancelAll",Si,void 0);
var Ti=m.n("yt.player.getPlayerByElement")||m.Kg;m.l("yt.player.getPlayerByElement",Ti,void 0);var Ui=m.n("yt.player.exports.feedbackStart")||m.vf;m.l("yt.player.exports.feedbackStart",Ui,void 0);var Vi=m.n("yt.player.exports.feedbackShowArticle")||m.yf;m.l("yt.player.exports.feedbackShowArticle",Vi,void 0);var Wi=m.n("yt.util.activity.init")||m.we;m.l("yt.util.activity.init",Wi,void 0);var Xi=m.n("yt.util.activity.getTimeSinceActive")||m.ye;m.l("yt.util.activity.getTimeSinceActive",Xi,void 0);
var Yi=m.n("yt.util.activity.setTimestamp")||xe;m.l("yt.util.activity.setTimestamp",Yi,void 0);var Ng,Xg,Sg,Zg,Rg,Ug;m.Yg=null;Zg="";Rg=0;Ug=[];var bh=[];var hh,Bh,Ch,ih,kh,sh,mh,oh,vh;ih=0;kh=[900,60,"waiting"];sh=[500,99,"waiting"];mh=[300,60,"waiting"];oh=[400,99,"waiting"];vh=[300,101,"done"];window.yt=window.yt||{};m.l("yt.setConfig",m.Za,void 0);m.l("yt.getConfig",m.w,void 0);m.l("yt.hasMsg",m.gb,void 0);m.l("yt.pubsub.publish",m.B,void 0);m.l("yt.pubsub.subscribe",m.z,void 0);m.l("yt.setMsg",function(a){$a(m.hb,arguments)},void 0);m.l("yt.setGoogMsg",function(a){$a(m.hb,arguments)},void 0);
m.l("reportTimingMaps",function(a,b,c,d){if(a)for(var e in a)m.Sc(e,a[e],d);if(c)for(var f in c)if("number"==typeof c[f])a=f,e=c[f],bd(d).span[a]=e;else{a=f;e=c[f];var h=d,k=bd(h).span,h=Tc(h);e in h&&(k[a]=(0,m.I)()-h[e])}if(b)for(var p in b)c=p,f=b[p],Xc(d)[c]=f;return Vc(!1,d)},void 0);m.l("yt.timing.report",jd,void 0);
m.l("yt.timing.reportAdToVideo",function(a,b,c){c={v:2,s:"youtube",action:c?"watch,ad2video_html5":"watch,ad2video"};a.aft=a.pbs=a.astv||a.actv;var d=[],e;for(e in a)"_"!=e.charAt(0)&&d.push(e+"."+a[e]);c.rt=d.join(",");for(var f in b)"_"!=f.charAt(0)&&(c[f]=b[f]);a=m.w("TIMING_INFO")||{};"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);cd(c)},void 0);m.t(Dh,m.qd);
Dh.prototype.enable=function(){window.onload=dh;window.onunload=eh;window.onerror=fh;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfrequest",gh),window.addEventListener("spfpartprocess",lh),window.addEventListener("spfpartdone",qh),window.addEventListener("spfprocess",rh),window.addEventListener("spfdone",th),window.addEventListener("spferror",wh),window.addEventListener("spfreload",xh),window.addEventListener("spfjsbeforeunload",Eh)),a.config=a.config||{},
window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",yh),this.subscribe("dispose",Ah)):window.spf.dispose();this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
Dh.prototype.init=function(){Dh.H.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();var a=window.ytPageFrameLoaded||!1,b,c;!a&&m.w("PAGEFRAME_JS")?(b=m.w("PAGEFRAME_JS"),c=function(){m.n("ytbin.www.pageframe.setup")();window.ytPageFrameLoaded=!0}):a&&(a=m.n("yt.www.masthead.loadSearchbox"))&&a();var a=m.w("JS_COMMON_MODULE"),d=m.w("JS_PAGE_MODULES");if(window.ytdepmap)d||(d=[a]),a=m.w("JS_DELAY_LOAD",void 0),0<a?(m.db(this.j),this.j=m.x(function(){b&&m.yd(b,c);window.spf.script.require(d)},
a)):(b&&m.yd(b,c),window.spf.script.require(d));else{var e={};e[a]=d;a=m.w("JS_DELAY_LOAD",void 0);0<a?(m.db(this.j),this.j=m.x(function(){b&&m.yd(b,c);m.Bd(e)},a)):(b&&m.yd(b,c),m.Bd(e))}Lg();var a=!!m.n("yt.reactLoaded"),f=m.w("REACT_JS");!a&&f&&m.yd(f,function(){m.l("yt.reactLoaded",!0,void 0)})};
Dh.prototype.dispose=function(){m.db(this.j);var a=m.n("ytbin.www.pageframe.cancelSetup");a&&a();m.eb(Ng);if(a=m.Pg())a.removeEventListener("onReady",Og),a.removeEventListener("onStateChange",Og);Tg("dispose");Xg=null;m.eb(Sg);m.ob(Ug);Ug.length=0;Dh.H.dispose.call(this)};
Dh.prototype.disable=function(){Dh.H.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfrequest",gh),window.removeEventListener("spfpartprocess",lh),window.removeEventListener("spfpartdone",qh),window.removeEventListener("spfprocess",rh),window.removeEventListener("spfdone",th),window.removeEventListener("spferror",wh),window.removeEventListener("spfreload",xh),window.removeEventListener("spfjsbeforeunload",Eh));window.onload=null;window.onunload=null;window.onerror=null};
m.sd(new Dh);})(_yt_www);
